### ISSUE TITLE
Not all pages work correcty

### ISSUE THREAD

**Issue by fedorovplaton** [atye/wikitable-api#30]
https://www.wikitable2json.com/api/Чемпионат_Индии_по_футболу?lang=ru
returns [], but
https://ru.wikipedia.org/wiki/Чемпионат_Индии_по_футболу
has tables

**Comment by atye** [comment]
The code parses tables that contain the class `wikitable`. That page has tables that do not have that class for some reason. I'll see what can be done.

**Comment by atye** [comment]
@fedorovplaton 

This is fixed.
