### ISSUE TITLE
Should references be included?

### ISSUE THREAD

**Issue by LukePrior** [atye/wikitable-api#37]
I'm not sure how much use returning references are, as they don't actually link to the reference and instead just clutter the response requiring further processing to clean.

i.e. `"Roy Morgan[150]"` would that be better as `"Roy Morgan"`

Maybe make it an option at least if not the default?

**Comment by atye** [comment]
I left the parsing of the data very high level so the user can process whatever they want. I'll look into an option to clean references but it may be tricky.

**Comment by atye** [comment]
@LukePrior 

This should be fixed. You can now use the `cleanRef=true` query parameter.

https://www.wikitable2json.com/api/Opinion_polling_for_the_2022_Australian_federal_election?table=0&cleanRef=true

**Comment by LukePrior** [comment]
LGTM
