### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by LukePrior** [atye/wikitable-api#46]
I am trying to run the following code in a JSFiddle but am encountering a CORS error.

```
$.getJSON('https://www.wikitable2json.com/api/Opinion_polling_for_the_2022_Australian_federal_election?table=0&cleanRef=true', function(localData) {
  console.log(localData);
});
```

https://jsfiddle.net/vheb5sw0/

Any ideas?

**Comment by atye** [comment]
Should be fixed.

For security reasons, JSFiddle sets the `Origin` header so the server (my API) must set an appropriate header to allow a cross-origin response.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

**Comment by LukePrior** [comment]
Splendid!
